config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :pictures do
		collection do
			post :confirm
		end
	end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

	root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	validates :title, presence: true
	validates :image, presence: true
	belongs_to :user

	mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  PERMISSIBLE_ATTRIBUTES = %i(image image_cache)
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    @users = User.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
		if params[:back]
			@picture = Picture.new(picture_params)
		else
			@picture = Picture.new
		end
  end

	# def confirm
	# 	@picture = Picture.new(picture_params)
	# 	render :new if @picture.invalid?
  #   binding.pry
	# end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    # binding.pry
    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_path, notice: '投稿されました' }
        format.json { render :show, status: :created, location: @picture }
        NoticeMailer.sendmail_picture(@picture).deliver
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to pictures_path, notice: '編集されました' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :content, :image, :image_cache, :remove_image)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
	# def choose_new_or_edit
	# 	if action_name == 'new' || action_name == 'confirm'
	# 		confirm_pictures_path
	# 	elsif action_name == 'edit'
	# 		picture_path
	# 	end
	# end

	def post_img(picture)
		return image_tag(picture.image, alt: picture.title) if picture.image?

    unless picture.image.blank?
      img_url = picture.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: picture.title)
  end
end

app/views/pictures/_form.html.erb
<div class="form-wrapper">

	<%= form_for(@picture) do |f| %>
		<%= f.error_messages! %>
		<div class="form-box">
			<div class="form-group">
				<%= f.label :title, class: 'sr-only'%><br>
				<%= f.text_field :title, class: 'form-control', placeholder: 'タイトル' %>
			</div>
			<div class="form-group">
				<%= f.label :content, class: 'sr-only' %><br>
				<%= f.text_area :content, class: 'form-control', placeholder: '一言', rows: 1 %>
			</div>

			<div class="field">
		    <% if @picture.image? %>
		      <div class="thumbnail">
		      <%= image_tag @picture.image.url %>
		    	</div>
		  	<% end %><br>
			    <%= f.label :画像を選択 %><br>
			    <%= f.file_field :image %>
			    <%= f.hidden_field :image_cache %>
		  </div>
	  	<div class="field">
		    <% if @picture.persisted? && @picture.image? %>
		      <label>
			      <%= f.check_box :remove_image %>
			      画像を削除
			    </label>
		  	<% end %>
	  	</div>

			<div class="actions select-btn">
				<%= link_to "キャンセル", pictures_path, class: 'btn btn-danger' %>
				<%= f.submit class: 'btn btn-default', value: "投稿する" %>
			</div>
		</div>
	<% end %>

</div>

app/views/pictures/confirm.html.erb
	<h3>以下の内容で、送信する。</h3>

	<%= form_for(@picture) do |f| %>
		<%= f.hidden_field :title %>
		<%= f.hidden_field :content %>
		<p>タイトル:<%= @picture.title %></p>
		<p>出来事:<%= @picture.content %></p>
		<%= f.submit "投稿する", class: "btn btn-default" %>
	<% end %>

	<%= form_for(@picture, url: new_picture_path, method: 'get') do |f| %>
		<%= f.hidden_field :title %>
		<%= f.hidden_field :content %>
		<%= f.submit "キャンセル", class: "btn btn-danger", name: 'back' %>
	<% end %>

app/views/pictures/edit.html.erb
<div class="left-wrapper">
  <h3>投稿編集</h3>
</div>

<%= render 'form' %>

app/views/pictures/index.html.erb
<%= link_to '新規投稿', new_picture_path, class: 'btn btn-default btn-lg btn-block new-btn' %><br />

<div class="imagine-wrapper">
  <% @pictures.reverse_each do |picture| %>
    <div class="imagine-box">
      <div class="poster-wrapper">
        <%= profile_img(picture.user) if profile_img(picture.user) %>
        <h4 class=""><%= picture.user.name %></h4>
      </div>
      <div class="content-wrapper">
        <div>タイトル：<%= picture.title %></div>
        <div><%= picture.content %></div>
        <%= post_img(picture) %>
      </div>
      <div class="select-box">
        <%= link_to 'Edit', edit_picture_path(picture), class: 'btn btn-success' %>
        <%= link_to 'Destroy', picture, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<div class="left-wrapper">
  <h3>新規投稿</h3>
</div>

<%= render 'form' %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>